config.steps = [
  { name: 'step1', label: 'step 1. init' },
  { name: 'step2', label: 'step 2. add' },
  { name: 'step3', label: 'step 3. commit' },
  { name: 'step4', label: 'step 4. commit 2' },
  { name: 'step5', label: 'step 5. branch' },
  { name: 'step6', label: 'step 6. checkout' },
  { name: 'step7', label: 'step 7. commit to branch' },
  { name: 'step8', label: 'step 8. fast forward merge' },
  { name: 'step9', label: 'step 9. reset' },
  { name: 'step10', label: 'step 10. reset 2' },
  { name: 'step11', label: 'step 11. commit to branch 2' },
  { name: 'step12', label: 'step 12. merge' },
  { name: 'step13', label: 'step 13. remote add' },
  { name: 'step14', label: 'step 14. fetch' },
  { name: 'step15', label: 'step 15. merge remote' },
  { name: 'step16', label: 'step 16. lightweigt tag' },
  { name: 'step17', label: 'step 17. annotated tag' },
  { name: 'step18', label: 'step 18. stash' },
  { name: 'step19', label: 'step 19. stash 2' },
  { name: 'step20', label: 'step 20. stash pop' },
  { name: 'step21', label: 'step 21. stash pop 2' },
  { name: 'step22', label: 'step 22. tree' },
  { name: 'step23', label: 'step 23. tree 2' },
  { name: 'step24', label: 'step 24. rebase' },
  { name: 'step25', label: 'step 25. rebase 2' },
  { name: 'step26', label: 'step 26. detached head' },
  { name: 'step27', label: 'step 27. detached head 2' },
  { name: 'step28', label: 'step 28. detached head 3' },
];
